### ISSUE TITLE
Question about the metric calculation in Table 3.

### ISSUE THREAD

**Issue by UNi13TS** [Yangziyu/NPF200#2]
Great work!
I have a question about the metric calculation in Table 3.
In Table 3, the results in 'Average' columns are calculated by weighting the number of frames of game and cartoon videos.
How about the 'Cartoon' and 'Game' columns?
Are they divided by the number of frames or just by the number of videos?

**Comment by Yangziyu** [comment]
They are divided by the number of frames.

**Comment by UNi13TS** [comment]
Hi,
Thanks for your reply.
